### ISSUE TITLE
Delete/disable blue "i" Message

### ISSUE THREAD

**Issue by ChrisTorng** [OSSIndex/audit.net#1]
For "A blue 'i' indicates a past vulnerability that is not expected to affect the installed package", that means this "Message" is useless to me. I hope never see them. Just delete this message, or at least let me disable them from Options setting.

**Comment by OSSIndex** [comment]
Thank you for the feedback. You are quite correct, most people will get no value from these extraneous messages so for now I have removed them. Perhaps in a future version I will make it configurable, but I would guess it will not be a highly requested feature.

The code fix has been pushed. I will create a new release on the weekend, at which point I will close the issue report.

**Comment by OSSIndex** [comment]
Release 1.2.5 has been pushed to [Visual Studio Gallery](https://visualstudiogallery.msdn.microsoft.com/73493090-b219-452a-989e-e3d228023927)

Thanks again for the feedback.
