### ISSUE TITLE
Provide a vulnerability details link or window

### ISSUE THREAD

**Issue by OSSIndex** [OSSIndex/audit.net#10]
If you check out the code in the 2.0.x branch (or download the appropriate 2.0.0 plugin) you will see that we now provide a reference for the vulnerability. Like so:

![image](https://cloud.githubusercontent.com/assets/13612752/23200916/ff9ee172-f8a4-11e6-9490-037665e9d77e.png)

It would be splendid if that could be a clickable link, but I do not think that is possible. Regardless, it would be nice if one of the following could occur (in order of preference?)

1. The link be clickable so that the user can go to the suggested HTML page for more details.
2. A context menu item was available to go to the suggested HTML page
3. Some other mechanism was made possible to go to the suggested HTML page.

I think the context menu might be cleanest, but I don't think people would look for it. The clickable link would be more obvious, but I don't think it is possible.

**Comment by aleksandert** [comment]
There is context menu item "Show error help" in Error list that uses default browser to open details page:

![Uploading show_error_help.png…]()

It is true that clickable link would be a better options but unfortunately they are not supported in error list.

**Comment by OSSIndex** [comment]
Ha, I forgot about this (or didn't know about it) -- its been a while since I tried to look at details. As I curate the vulnerability lists I never really need to look deeper to know about the vulnerabilities.

Thanks.
