### ISSUE TITLE
Vulnerability history found but nothing in Error List

### ISSUE THREAD

**Issue by VitoHanoi** [OSSIndex/audit.net#16]
Hey,

I'm new with this package. I installed it on VS2017 and ran it manually on my project after having all my nugget packages installed (project is nearly over).

In the output Console, I have some package vulnerabilities but when I go to my Error list there is nothing. Any idea why? In the warning there is nothing linked to Audit.Net as well...
But my nugget packages are quite old and maybe it is just some warnings about the versions I'm using?

![untitled](https://user-images.githubusercontent.com/16385289/33853727-dbf15c26-df23-11e7-83b3-e94d6a78c212.png)

Thanks A lot,
Guillaume

**Comment by OSSIndex-Admin** [comment]
Unfortunately I am traveling at the moment so cannot double check (my Windows dev machine is at home). I am reasonably sure that this means that there are no "active" vulnerabilities. Some of your dependencies had vulnerabilities in the past but none are affecting the installed versions.

Once I get home I will do some testing to ensure I am remembering correctly. If you have active vulnerabilities they should definitely be showing in your errors tab (which should come to the front automatically in that situation).

**Comment by VitoHanoi** [comment]
Thank you for your answer. 
It was more a question as nothing is breaking the build...

**Comment by markusschaber** [comment]
I have the same problem - it may be due to some other Visual Studio extensions I installed (including ReSharper), I'm on the newest stable branch of VS 2017: 15.5.3.

**Comment by OSSIndex-Admin** [comment]
I think there is some confusion about the UI. I have a change I think would be worth doing to make things more clear, but want to run it by you (and get a bit more information) to make sure there is no underlying problem.

I am seeing text similar to the following in the "output" tab, using VS 2017: 15.5.2:

![screenshot0](https://user-images.githubusercontent.com/13612752/34922452-5afb5bc8-f966-11e7-85c8-2e3a5a9fe271.png)

But the error tab is blank. This project has no packages that have live/active vulnerabilities. There are packages for which previous versions have vulnerabilities, but nothing in the current versions. This is not explained particularly well in the output text. It is also not possible to see the vulnerability history anywhere -- we used to show the old (non-applicable) vulnerabilities as "info" rows in the error list, but this was proving to be confusing and also clutters things up.

One way to test to ensure we are actually reporting vulnerabilities correctly is to add a known vulnerable package. My go-to package is jquery, version 1.9, which gives me these errors:

![screenshot1](https://user-images.githubusercontent.com/13612752/34922496-0df41f76-f967-11e7-951d-52800b82ac6d.png)

It would be splendid if you could give this a shot and see if you get vulnerabilities displayed. If not then please let me know and I will do some more in depth debugging.

Meanwhile, I would suggest the following possible changes:

- In the "output" window, do one of the following:
  - don't bother mentioning package's history, just the number with vulnerabilities.
  - mention history, but be more explicit: "History found for 1 package(s): 0 active vulnerabilities"
- In the "Error list" window, when there are no vulnerabilities have an "info" line that says "Vulnerability audit successful, no vulnerabilities found."

What do you think?

**Comment by VitoHanoi** [comment]
Hey @OSSIndex-Admin ,

Thanks for your answer, I'm sorry for the delay. I wasn't aware that someone had continued this thread after your first answer. This is what I get when adding JQuery

![image](https://user-images.githubusercontent.com/16385289/36559943-48a15de2-1874-11e8-9250-75a1e619546a.png)

![image](https://user-images.githubusercontent.com/16385289/36559957-50d8e00c-1874-11e8-9246-efd07b118adc.png)

So, I believe my version of Audit.Net is working (behave like yours) 

Your changes are perfectly fine and will be well received by our team avoiding any confusion.

Thanks again.
You can close the issue once read this.
Guillaume

**Comment by ken-duck** [comment]
Terrific! Thanks for the notification and feed back.

**Comment by NeilBostrom** [comment]
> But the error tab is blank. This project has no packages that have live/active vulnerabilities. There are packages for which previous versions have vulnerabilities, but nothing in the current versions. This is not explained particularly well in the output text. It is also not possible to see the vulnerability history anywhere -- we used to show the old (non-applicable) vulnerabilities as "info" rows in the error list, but this was proving to be confusing and also clutters things up.

This massively confused me when I first use it and I had to the exact same thing, add a known vulnerable package to check it was working.

>   * mention history, but be more explicit: "History found for 1 package(s): 0 active vulnerabilities"

This would have helped me understand the results much quicker.

**Comment by ken-duck** [comment]
I will be revisiting audit.net shortly to upgrade it to Visual Studio 2019, at which time I will also explore if there are ways we can improve the presentation.

**Comment by ken-duck** [comment]
I spent a bit of time looking into the presentation, and it occurs to me that we cannot make the "info" historical data available due to changes in the OSS Index API, so I will not be improving the presentation using that data (or at least not in that way).

**Comment by NeilBostrom** [comment]
Shame, any chance of improving the messaging output to list the vulnerabilities instead of showing them in the error window only? Be great to list them in the output in the same way the scan shows in the output window.

**Comment by ken-duck** [comment]
Whoops. Missed your response.

And it should definitely be possible to add the vulnerabilities to the message window. I will make a new issue for that and try and make the change shortly. It may even be something I can do instead of waiting for our main C# dev to get back to (he is working on a few other issues at the moment).

**Comment by ken-duck** [comment]
Added here: https://github.com/OSSIndex/audit.net/issues/28

**Comment by Prashant-Kan** [comment]
I am facing the same issue, Audit Packages shows 1 Vulnerability but the Error List is blank
any solution ?

**Comment by ken-duck** [comment]
Its possible I just need to release a new version. I will look into it today.

**Comment by ken-duck** [comment]
Created new issue to track this here: https://github.com/OSSIndex/audit.net/issues/35

**Comment by allisterb** [comment]
@NeilBostrom @VitoHanoi Hi I believe I found the issue...just to confirm this happens when auditing .NET Core and .NET Standard projects right?
The older .NET Framework projects should be ok.

**Comment by allisterb** [comment]
I've attached a build that should partially resolve the issue (just remove the .zip extension.) The problem basically is with new-style .NET projects which don't specify their packages in a packages.confg or in the project file. The Error display in VS.NET relies on a source file location so packages with no file need an alternate method for being displayed in the Error window. 
[NugetAuditor.VSIX.vsix.zip](https://github.com/OSSIndex/audit.net/files/4115452/NugetAuditor.VSIX.vsix.zip)

**Comment by rebelinspokane** [comment]
WHERE are the messages
Vulnerability history found for 11 package(s). See Error List for active vulnerability details.
Nothing in error tab

**Comment by denastro** [comment]
@rebelinspokane Thanks for bringing this up. Unfortunately, the tool is currently not supported by Sonatype. We are relying on community help to tackle issues that may arise.
