### ISSUE TITLE
Command Line Interface?

### ISSUE THREAD

**Issue by russplaysguitar** [OSSIndex/audit.net#17]
I'd like to get this running automatically via the command line, but it looks like it only runs as a Visual Studio extension. Is this correct?

**Comment by OSSIndex-Admin** [comment]
You are correct. However, there is a command client called [DevAudit](https://github.com/OSSIndex/DevAudit) which can do everything Audit.net can do and much, much more.

**Comment by russplaysguitar** [comment]
Great, thanks!
