### ISSUE TITLE
Audit errors not shown in Error List tab

### ISSUE THREAD

**Issue by tomgron** [OSSIndex/audit.net#18]
In VS2015 I don't get list of auditing errors in Errors List tab. Build shows that I have vulnerabilities but I can't see which packages are affected. I have ReSharper, Coderush and lots of other extensions installed - could they block for some reason the visibility of the errors in the list ?

**Comment by ken-duck** [comment]
Hi.

I think that this isn't actually a bug, but as problem with the current UI being confusing. See the description here (https://github.com/OSSIndex/audit.net/issues/16#issuecomment-357555383) and let me know if that is what is happening.

This has come up a few times. I will try and put out an update that clarifies the issue some. I am leaving this report open to track the feature.

**Comment by ken-duck** [comment]
Just an FYI. We have a new API version at OSS Index and I will be upgrading the plugin in the near future. At that time I will update the UI as well to be less confusing.
