### ISSUE TITLE
Inspecting package dependencies

### ISSUE THREAD

**Issue by EricStG** [OSSIndex/audit.net#21]
When auditing a project using the newer csproj format, it seems like Audit.net only looks at the first level of dependencies.
Ex: Project depends on package A, which depends on package B, but only package A gets audited.

Is that by design or am I missing something?

Tested against .net core and standard projects.

**Comment by ken-duck** [comment]
it is quite possible that is what it is doing at the moment, but definitely not how we want it to act. I will explore some options and see if I can figure out how to get the full dependency tree. I am open to any suggestions.

**Comment by EricStG** [comment]
It looks like `dotnet oudated` is using MSBuild to get the full dependency tree (https://github.com/jerriep/jerriepelser.com/blob/master/content/blog/2018-06-20-analyze-dotnet-project-dependencies-part-1.md)
An alternative would be to tag in the Nuget client API, but I couldn't find any obvious way to use it.

**Comment by ken-duck** [comment]
Gives me some ideas what to look for.

I am away on business for the week, so don't have access to my dev box. I *can* research some alternatives though. Thanks for the tip! We'll see what comes up.

**Comment by OSSIndex-Admin** [comment]
FYI, I am currently working on a solution. For now the simplest method appears to be loading the dependency information directly using the NuGet REST API. If this works then it is the most flexible option.

**Comment by OSSIndex-Admin** [comment]
Version 3.0.2 has been released which should resolve this problem. It runs a little slower the first time since it needs to fetch a bunch of dependencies, but the dependencies are cached to reduce the speed hit for subsequent usage.

**Comment by OSSIndex-Admin** [comment]
Thanks for the report!

**Comment by EricStG** [comment]
There might be an issue with dependency resolution. Running against a single project, I can see the list of dependencies in the Audit.Net console, but I see multiple versions of the same packages.
ex:
```
  * System.Threading@4.0.0
  * System.Threading@4.0.10
  * System.Threading@4.0.11
  * System.Threading@4.3.0
```
But if I look at `project.assets.json`, it was resolved to `System.Threading@4.3.0`, and that's the actual dependency.

**Comment by ken-duck** [comment]
Sorry for the delay. Chaotic week for me. I will dig in a bit. What could be happening is the additional versions may be recursive included by some of your other dependencies.
