### ISSUE TITLE
REST API doesn't support scopes with @ (at sign).

### ISSUE THREAD

**Issue by danielsimao** [OSSIndex/audit.net#29]
I came across an issue regarding @ when I was trying to access information about https://www.npmjs.com/package/@zeit/next-css. 

Purl-spec supports this kind of scope in the following way: `pkg:npm/%40zeit/next-css@1.0.1`.

Is there any way of accessing this kind of scope or it is not supported by the API?

**Comment by ken-duck** [comment]
Thanks for the report. The API does not currently support scopes, as you have noted. This is something we definitely want to fix; thanks for drawing our attention to the problem.
