### ISSUE TITLE
Provide more fine grained vulnerability requests for packages

### ISSUE THREAD

**Issue by OSSIndex** [OSSIndex/audit.net#3]
Consider the Nancy Project: https://ossindex.net/resource/project/8398863527

There are multiple packages. The vulnerabilities are actually related to the main "Nancy" package only, but get reported for all of the dependencies.

Though in this case every package can be upgraded past the "vulnerable" version, the results of Audit.NET are misleading.

**Comment by aleksandert** [comment]
Is this still relevant when OSSIndex API 2.0 is used?

**Comment by OSSIndex** [comment]
You are quite correct, this is no longer applicable.
