### ISSUE TITLE
Extension crashes VS 2017 on opening of project

### ISSUE THREAD

**Issue by OSSIndex** [OSSIndex/audit.net#8]
I installed the 2.0.0 version of the extension on the VS2017 release candidate. Upon opening a project, I got the following error:

![image](https://cloud.githubusercontent.com/assets/13612752/23199398/1e101d6e-f89c-11e6-9eaa-281047456e11.png)

I did some debugging and updated the code to narrow down the problem (see the v2.0.x branch). I got the following information from debugging:

![image](https://cloud.githubusercontent.com/assets/13612752/23199884/2c961c0a-f89f-11e6-9b31-421b175648d5.png)

At this point, I added in a terrible kludge to prevent the crash

![image](https://cloud.githubusercontent.com/assets/13612752/23199941/87793990-f89f-11e6-8414-04f3cd64e508.png)

This allows the extension to seemingly work correctly, but catching a null pointer exception is a terrible kludge which we need to remove.

**Comment by aleksandert** [comment]
This one should be fixed now. I'm using project.kind to test if a project supports nuget packages.
